"""Added TaskActivity and User model changes

Revision ID: bfc65802adc5
Revises: bb2c4d5a9ebe
Create Date: 2024-09-10 16:48:45.161556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfc65802adc5'
down_revision: Union[str, None] = 'bb2c4d5a9ebe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('sub_category_id', sa.Integer(), nullable=True),
    sa.Column('sub_category_name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_groups_id'), 'activity_groups', ['id'], unique=False)
    op.create_table('activity_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_types_id'), 'activity_types', ['id'], unique=False)
    op.create_table('core_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_core_groups_id'), 'core_groups', ['id'], unique=False)
    op.create_table('related_entities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('picture_id', sa.Integer(), nullable=True),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_related_entities_id'), 'related_entities', ['id'], unique=False)
    op.create_table('stages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stages_id'), 'stages', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('picture_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks_activity.task_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attachments_id'), 'attachments', ['id'], unique=False)
    op.add_column('tasks_activity', sa.Column('created_by_id', sa.Integer(), nullable=False))
    op.add_column('tasks_activity', sa.Column('assigned_to_id', sa.Integer(), nullable=True))
    op.alter_column('tasks_activity', 'task_description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('tasks_activity', 'notes',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('tasks_activity', 'favorite',
               existing_type=sa.VARCHAR(length=5),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.create_foreign_key(None, 'tasks_activity', 'users', ['assigned_to_id'], ['id'])
    op.create_foreign_key(None, 'tasks_activity', 'stages', ['stage_id'], ['id'])
    op.create_foreign_key(None, 'tasks_activity', 'users', ['created_by_id'], ['id'])
    op.create_foreign_key(None, 'tasks_activity', 'activity_groups', ['activity_group_id'], ['id'])
    op.create_foreign_key(None, 'tasks_activity', 'activity_types', ['activity_type_id'], ['id'])
    op.create_foreign_key(None, 'tasks_activity', 'core_groups', ['core_group_id'], ['id'])
    op.drop_column('tasks_activity', 'related_to')
    op.drop_column('tasks_activity', 'created_by')
    op.drop_column('tasks_activity', 'related_to_company')
    op.drop_column('tasks_activity', 'attachments')
    op.drop_column('tasks_activity', 'core_group_category_id')
    op.drop_column('tasks_activity', 'activity_type_name')
    op.drop_column('tasks_activity', 'core_group_name')
    op.drop_column('tasks_activity', 'key')
    op.drop_column('tasks_activity', 'activity_group_sub_category_name')
    op.drop_column('tasks_activity', 'core_group_category')
    op.drop_column('tasks_activity', 'assigned_to')
    op.drop_column('tasks_activity', 'related_to_picture_id')
    op.drop_column('tasks_activity', 'activity_group_name')
    op.drop_column('tasks_activity', 'assigned_to_email')
    op.drop_column('tasks_activity', 'assigned_to_company')
    op.drop_column('tasks_activity', 'assigned_to_picture_id')
    op.drop_column('tasks_activity', 'session_id')
    op.drop_column('tasks_activity', 'related_to_email')
    op.drop_column('tasks_activity', 'activity_group_sub_category_id')
    op.drop_column('tasks_activity', 'modified_by')
    op.drop_column('tasks_activity', 'stage_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks_activity', sa.Column('stage_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('tasks_activity', sa.Column('modified_by', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('tasks_activity', sa.Column('activity_group_sub_category_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('tasks_activity', sa.Column('related_to_email', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('tasks_activity', sa.Column('session_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('tasks_activity', sa.Column('assigned_to_picture_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('tasks_activity', sa.Column('assigned_to_company', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('tasks_activity', sa.Column('assigned_to_email', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('tasks_activity', sa.Column('activity_group_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('tasks_activity', sa.Column('related_to_picture_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('tasks_activity', sa.Column('assigned_to', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('tasks_activity', sa.Column('core_group_category', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('tasks_activity', sa.Column('activity_group_sub_category_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('tasks_activity', sa.Column('key', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('tasks_activity', sa.Column('core_group_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('tasks_activity', sa.Column('activity_type_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('tasks_activity', sa.Column('core_group_category_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('tasks_activity', sa.Column('attachments', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('tasks_activity', sa.Column('related_to_company', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('tasks_activity', sa.Column('created_by', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('tasks_activity', sa.Column('related_to', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'tasks_activity', type_='foreignkey')
    op.drop_constraint(None, 'tasks_activity', type_='foreignkey')
    op.drop_constraint(None, 'tasks_activity', type_='foreignkey')
    op.drop_constraint(None, 'tasks_activity', type_='foreignkey')
    op.drop_constraint(None, 'tasks_activity', type_='foreignkey')
    op.drop_constraint(None, 'tasks_activity', type_='foreignkey')
    op.alter_column('tasks_activity', 'favorite',
               existing_type=sa.Boolean(),
               type_=sa.VARCHAR(length=5),
               existing_nullable=True)
    op.alter_column('tasks_activity', 'notes',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('tasks_activity', 'task_description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('tasks_activity', 'assigned_to_id')
    op.drop_column('tasks_activity', 'created_by_id')
    op.drop_index(op.f('ix_attachments_id'), table_name='attachments')
    op.drop_table('attachments')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_stages_id'), table_name='stages')
    op.drop_table('stages')
    op.drop_index(op.f('ix_related_entities_id'), table_name='related_entities')
    op.drop_table('related_entities')
    op.drop_index(op.f('ix_core_groups_id'), table_name='core_groups')
    op.drop_table('core_groups')
    op.drop_index(op.f('ix_activity_types_id'), table_name='activity_types')
    op.drop_table('activity_types')
    op.drop_index(op.f('ix_activity_groups_id'), table_name='activity_groups')
    op.drop_table('activity_groups')
    # ### end Alembic commands ###
